### ISSUE TITLE
RFC: app-server architecture / tech to use

### ISSUE THREAD

**Issue by achuie** [achuie/cookbook#1]
Potential libraries to use:

backend server: https://pypi.org/project/Flask/

frontend: https://react-bootstrap.github.io/

**Comment by the-tarin** [comment]
Backend: Django 
Frontend: Potentially React, however, we can just use Django to showcase Python

**Comment by achuie** [comment]
I don’t know what you mean by “showcase Python”

here’s a comparison of django and flask: https://www.codecademy.com/resources/blog/flask-vs-django/

Per the article, django has more batteries included which we probably don’t need, but I’m not opposed to it. Ease of use is good to prioritize, and I’m not bothered by all the python dependencies as I plan on using nix to manage the dev env anyway.

**Comment by achuie** [comment]
Decided on django offline.
